[build]
  command = "npm run prerender"
  functions = "./functions"
  publish = "dist/home/browser"

[[plugins]]
package = "netlify-plugin-a11y"
  [plugins.inputs]
  checkPaths = ['/']
[[plugins]]
package = "@sentry/netlify-build-plugin"

[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = '''
  base-uri 'self';
  default-src 'self';
  connect-src 'self' https://o544339.ingest.sentry.io;
  font-src https://fonts.gstatic.com https://rsms.me/inter/font-files/;
  form-action 'none';
  frame-ancestors 'none';
  img-src 'self';
  object-src 'none';
  script-src 'self' https://o544339.ingest.sentry.io;
  script-src-elem 'self' https://o544339.ingest.sentry.io;
  style-src 'self' 'unsafe-inline';
  style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com https://rsms.me/inter/inter.css;
  report-uri https://o544339.ingest.sentry.io/api/5665484/security/?sentry_key=36e2e5d5b38b4d52b2056ea49bf895c4;
  '''
  Expect-CT = "max-age=86400, enforce, report-uri'=https://o544339.ingest.sentry.io/api/5665484/security/?sentry_key=36e2e5d5b38b4d52b2056ea49bf895c4'"
  Feature-Policy = "microphone 'none'; camera 'none'"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Strict-Transport-Security = "max-age=31536000; includesSubDomains; preload"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
