[settings]
ID = "b22b9fef-dc15-42e1-961f-feaa2237a8d6"

[build]



[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
      max-age=0,
      no-cache,
      no-store,
      must-revalidate
    '''
    Content-Security-Policy = "default-src 'self'; connect-src 'self' ; img-src 'self'; script-src 'self'; style-src 'self'; report-uri https://o544339.ingest.sentry.io/api/5665484/security/?sentry_key=36e2e5d5b38b4d52b2056ea49bf895c4"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
