[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
    default-src 'self';
    connect-src 'self' https://o544339.ingest.sentry.io;
    form-action 'none';
    frame-ancestors 'none';
    img-src 'self';
    script-src 'self' https://o544339.ingest.sentry.io;
    style-src 'self';
    report-uri https://o544339.ingest.sentry.io/api/5665484/security/?sentry_key=36e2e5d5b38b4d52b2056ea49bf895c4;
    '''
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"